// <auto-generated />
using JobFinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace JobFinder.Data.Migrations
{
    [DbContext(typeof(JobFinderDbContext))]
    [Migration("20180430193736_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JobFinder.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentType");

                    b.Property<DateTime>("DateUploaded");

                    b.Property<byte[]>("FileData");

                    b.Property<string>("FileName")
                        .IsRequired();

                    b.Property<long>("FileSize");

                    b.Property<bool?>("IsApproved");

                    b.Property<int>("JobOfferId");

                    b.Property<string>("PersonId")
                        .IsRequired();

                    b.Property<int?>("PersonId1");

                    b.HasKey("Id");

                    b.HasIndex("JobOfferId");

                    b.HasIndex("PersonId1");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("JobFinder.Models.BusinessSector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BusinessSectors");
                });

            modelBuilder.Entity("JobFinder.Models.JobOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApplicationsCount");

                    b.Property<int>("BusinessSectorId");

                    b.Property<string>("CompanyId");

                    b.Property<int?>("CompanyId1");

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<bool?>("IsFullTime");

                    b.Property<bool?>("IsPermanent");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<int>("TownId");

                    b.Property<int>("Views");

                    b.HasKey("Id");

                    b.HasIndex("BusinessSectorId");

                    b.HasIndex("CompanyId1");

                    b.HasIndex("TownId");

                    b.ToTable("JobOffers");
                });

            modelBuilder.Entity("JobFinder.Models.PersonOffer", b =>
                {
                    b.Property<int>("PersonId");

                    b.Property<int>("JobOfferId");

                    b.HasKey("PersonId", "JobOfferId");

                    b.HasIndex("JobOfferId");

                    b.ToTable("PersonOffer");
                });

            modelBuilder.Entity("JobFinder.Models.SectorCompany", b =>
                {
                    b.Property<int>("BusinessSectorId");

                    b.Property<int>("CompanyId");

                    b.HasKey("BusinessSectorId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("SectorCompany");
                });

            modelBuilder.Entity("JobFinder.Models.Town", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Towns");
                });

            modelBuilder.Entity("JobFinder.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Password");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("JobFinder.Models.Company", b =>
                {
                    b.HasBaseType("JobFinder.Models.User");

                    b.Property<string>("AboutUs");

                    b.Property<string>("Address");

                    b.Property<string>("Bulstat")
                        .IsRequired()
                        .HasMaxLength(13);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<bool>("IsApproved");

                    b.Property<string>("WebSite");

                    b.HasIndex("Bulstat")
                        .IsUnique()
                        .HasFilter("[Bulstat] IS NOT NULL");

                    b.HasIndex("CompanyName")
                        .IsUnique()
                        .HasFilter("[CompanyName] IS NOT NULL");

                    b.ToTable("Companies");

                    b.HasDiscriminator().HasValue("Company");
                });

            modelBuilder.Entity("JobFinder.Models.Person", b =>
                {
                    b.HasBaseType("JobFinder.Models.User");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.ToTable("People");

                    b.HasDiscriminator().HasValue("Person");
                });

            modelBuilder.Entity("JobFinder.Models.Application", b =>
                {
                    b.HasOne("JobFinder.Models.JobOffer", "JobOffer")
                        .WithMany("Applications")
                        .HasForeignKey("JobOfferId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JobFinder.Models.Person", "Person")
                        .WithMany("Applications")
                        .HasForeignKey("PersonId1");
                });

            modelBuilder.Entity("JobFinder.Models.JobOffer", b =>
                {
                    b.HasOne("JobFinder.Models.BusinessSector", "BusinessSector")
                        .WithMany()
                        .HasForeignKey("BusinessSectorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JobFinder.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId1");

                    b.HasOne("JobFinder.Models.Town", "Town")
                        .WithMany("JobOffers")
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobFinder.Models.PersonOffer", b =>
                {
                    b.HasOne("JobFinder.Models.JobOffer", "JobOffer")
                        .WithMany("PeopleFollowing")
                        .HasForeignKey("JobOfferId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JobFinder.Models.Person", "Person")
                        .WithMany("FollowedOffers")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobFinder.Models.SectorCompany", b =>
                {
                    b.HasOne("JobFinder.Models.BusinessSector", "BusinessSector")
                        .WithMany("Companies")
                        .HasForeignKey("BusinessSectorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JobFinder.Models.Company", "Company")
                        .WithMany("BusinessSectors")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
